/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Role {
  createdDate?: string;
  idRole?: number;
  lastModifiedDate?: string;
  name?: string;
}
