/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Meeting } from '../../models/meeting';

export interface FollowupsNextActionFollowupIdGet$Params {
  followupId: number;
}

export function followupsNextActionFollowupIdGet(http: HttpClient, rootUrl: string, params: FollowupsNextActionFollowupIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'count'?: number;
'rows'?: Array<Meeting>;
}>> {
  const rb = new RequestBuilder(rootUrl, followupsNextActionFollowupIdGet.PATH, 'get');
  if (params) {
    rb.path('followupId', params.followupId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'count'?: number;
      'rows'?: Array<Meeting>;
      }>;
    })
  );
}

followupsNextActionFollowupIdGet.PATH = '/followups/next-action/{followupId}';
