/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface FollowupsCreatePost$Params {
      body: {
'start_date'?: string;
'Lead_idLead'?: number;
'outcome'?: string;
'notes'?: string;
'status'?: 'in_progress' | 'completed' | 'paused' | 'cancelled';
'priority'?: 'CRITICAL' | 'IMPORTANT' | 'HIGH' | 'MEDIUM' | 'LOW';
}
}

export function followupsCreatePost(http: HttpClient, rootUrl: string, params: FollowupsCreatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, followupsCreatePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

followupsCreatePost.PATH = '/followups/create';
