/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { ActivitiesService } from './services/activities.service';
import { BusinessesService } from './services/businesses.service';
import { CompetitorsService } from './services/competitors.service';
import { CompetitorHasBusinessService } from './services/competitor-has-business.service';
import { ContactsService } from './services/contacts.service';
import { ContactHasMeetingService } from './services/contact-has-meeting.service';
import { CountriesService } from './services/countries.service';
import { EnterprisesService } from './services/enterprises.service';
import { FollowupsService } from './services/followups.service';
import { AuthService } from './services/auth.service';
import { GatewaysService } from './services/gateways.service';
import { LeadsService } from './services/leads.service';
import { MeetingsService } from './services/meetings.service';
import { OrdersService } from './services/orders.service';
import { PlansService } from './services/plans.service';
import { ProductsService } from './services/products.service';
import { ProductCategoriesService } from './services/product-categories.service';
import { SourcesService } from './services/sources.service';
import { UsersService } from './services/users.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    ActivitiesService,
    BusinessesService,
    CompetitorsService,
    CompetitorHasBusinessService,
    ContactsService,
    ContactHasMeetingService,
    CountriesService,
    EnterprisesService,
    FollowupsService,
    AuthService,
    GatewaysService,
    LeadsService,
    MeetingsService,
    OrdersService,
    PlansService,
    ProductsService,
    ProductCategoriesService,
    SourcesService,
    UsersService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
