/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Meeting } from '../../models/meeting';

export interface MeetingsGetByBusinessBusinessIdGet$Params {
  businessId: number;
  page?: number;
  limit?: number;
}

export function meetingsGetByBusinessBusinessIdGet(http: HttpClient, rootUrl: string, params: MeetingsGetByBusinessBusinessIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'count'?: number;
'rows'?: Array<Meeting>;
}>> {
  const rb = new RequestBuilder(rootUrl, meetingsGetByBusinessBusinessIdGet.PATH, 'get');
  if (params) {
    rb.path('businessId', params.businessId, {});
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'count'?: number;
      'rows'?: Array<Meeting>;
      }>;
    })
  );
}

meetingsGetByBusinessBusinessIdGet.PATH = '/meetings/get-by-business/{businessId}';
