/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface MeetingsCreatePost$Params {
      body: {
'date'?: string;
'summary'?: string;
'next_action'?: string;
'next_action_date'?: string;
'due_date'?: string;
'title'?: string;
'_idFollowup'?: number;
'_idBusiness'?: number;
'contact_emails'?: string;
}
}

export function meetingsCreatePost(http: HttpClient, rootUrl: string, params: MeetingsCreatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, meetingsCreatePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

meetingsCreatePost.PATH = '/meetings/create';
