/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface BusinessHasCompetitorsLinkBusinessBusinessIdIdPut$Params {

/**
 * Competitor ID
 */
  id: number;

/**
 * Business ID
 */
  businessId: number;
      body: {
'market_position'?: string;
'weaknesses'?: string;
'strengths'?: string;
'reference_clients'?: string;
'risk_level'?: string;
}
}

export function businessHasCompetitorsLinkBusinessBusinessIdIdPut(http: HttpClient, rootUrl: string, params: BusinessHasCompetitorsLinkBusinessBusinessIdIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, businessHasCompetitorsLinkBusinessBusinessIdIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('businessId', params.businessId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

businessHasCompetitorsLinkBusinessBusinessIdIdPut.PATH = '/business-has-competitors/link-business/{businessId}/{id}';
