/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ActivitiesUpdateIdPut$Params {
  id: number;
      body: {
'title'?: string;
'detail'?: string;
'created_date'?: string;
'start_date'?: string;
'end_date'?: string;
'tags'?: string;
'priority'?: string;
'last_action'?: string;
'last_action_date'?: string;
'next_action'?: string;
'next_action_date'?: string;
'_idFollowup'?: number;
}
}

export function activitiesUpdateIdPut(http: HttpClient, rootUrl: string, params: ActivitiesUpdateIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, activitiesUpdateIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

activitiesUpdateIdPut.PATH = '/activities/update/{id}';
