/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Activity } from '../../models/activity';

export interface ActivitiesCreatePost$Params {
      body: {
'title'?: string;
'detail'?: string;
'created_date'?: string;
'start_date'?: string;
'end_date'?: string;
'tags'?: string;
'priority'?: string;
'last_action'?: string;
'last_action_date'?: string;
'next_action'?: string;
'next_action_date'?: string;
'_idFollowup'?: number;
'_idBusiness'?: number;
}
}

export function activitiesCreatePost(http: HttpClient, rootUrl: string, params: ActivitiesCreatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<Activity>> {
  const rb = new RequestBuilder(rootUrl, activitiesCreatePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Activity>;
    })
  );
}

activitiesCreatePost.PATH = '/activities/create';
