/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Business {
  approach?: string | null;
  business_type?: string | null;
  case_level?: string | null;
  case_started_date?: string | null;
  client_constraints?: string | null;
  closed_date?: string | null;
  current_supplier?: string | null;
  engagement_score?: number;
  idBusiness?: number;
  need?: string;
  notes?: string | null;
  potential_time_for_delivery?: string | null;
  previous_vc?: string | null;
  stage?: ('OPPORTUNITY' | 'PORPOSAL_SENT' | 'NEGOCIATION' | 'WON') | null;
  total_turnover?: string | null;
  turnover_signable?: string | null;
}
