/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Competitor {
  headquater_location?: string | null;
  idCompetitor?: number;
  last_updated?: string | null;
  name?: string;
  notes?: string | null;
  product_line?: string | null;
  reference_clients?: string | null;
  sector?: string | null;
  website?: string | null;
}
