/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Contact {
  assignedToUser?: number;
  email?: string | null;
  first_name?: string;
  idContact?: number;
  language?: string;
  last_name?: string;
  notes?: string | null;
  phone?: string | null;
  position?: string | null;
}
