/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Country {
  calling_code?: string | null;
  createdAt?: string;
  idCountry?: number;
  is_un_member?: boolean;
  iso2?: string | null;
  iso3?: string | null;
  long_name?: string;
  short_name?: string;
  updatedAt?: string;
}
