/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Enterprise {
  address?: string;
  contact_email?: string;
  email_domain?: string;
  expires_at?: string | null;
  idEnterprise?: number;
  is_archived?: boolean;
  is_verified?: boolean;
  logo?: string | null;
  name?: string;
  plan?: number;
  sector?: 'Technology' | 'Healthcare' | 'Education' | 'Finance' | 'Retail' | 'Logistics' | 'Manufacturing' | 'Media';
  slug?: string;
  subscription_status?: string;
  website?: string;
}
