/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Followup {
  followup_status?: 'Hot' | 'Warm' | 'Cold';
  idFollowup?: number;
  is_archived?: boolean;
  lead_score?: number;
  notes?: string;
  outcome?: string;
  priority?: 'CRITICAL' | 'IMPORTANT' | 'HIGH' | 'MEDIUM' | 'LOW';
  start_date?: string;
  status?: string;
}
