/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Gateway {
  charge?: number;
  comment?: string;
  created_at?: string;
  currency?: string;
  data?: string;
  id?: number;
  image_accept?: number;
  is_auto?: number;
  logo?: string;
  max_amount?: number;
  min_amount?: number;
  multiply?: number;
  name?: string;
  namespace?: string;
  phone_required?: number;
  status?: number;
  test_mode?: number;
  updated_at?: string;
}
