/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Lead {
  Country?: any;
  Source?: any;
  activitySector?: string;
  address?: string | null;
  assigned_to_user_id?: number | null;
  country?: number | null;
  createdAt?: string;
  creator?: any;
  date_assigned?: string | null;
  date_converted?: string | null;
  description?: string;
  email?: string | null;
  id?: number;
  is_archived?: boolean;
  is_private?: boolean;
  last_activity?: string | null;
  last_status_change?: string | null;
  lead_value?: number | null;
  name?: string;
  status?: 'UNQUALIFIED' | 'QUALIFIED' | 'CONVERTED';
  tags?: string | null;
  telephone?: string | null;
  town?: string | null;
  updatedAt?: string;
  website?: string | null;
}
