/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Meeting {
  '_idBusiness'?: number | null;
  '_idFollowup'?: number | null;
  due_date?: string;
  idMeeting?: number;
  next_action?: string;
  next_action_date?: string | null;
  status?: 'COMPLETED' | 'PENDING' | 'IN_PROGRESS' | 'NOT STARTED' | 'WAITING FEEDBACK';
  summary?: string;
  title?: string;
}
