/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Order {
  amount?: number;
  created_at?: string;
  gateway_id?: number;
  id?: number;
  invoice_no?: string;
  meta?: string;
  payment_id?: string;
  plan_id?: number;

  /**
   * 0 = pending, 1 = paid
   */
  status?: number;
  tax?: number;
  updated_at?: string;
  user_id?: number;
  will_expire?: string;
}
