/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Plan {
  created_at?: string;
  data?: string;
  days?: number;
  iconname?: string;
  id?: number;
  is_archived?: boolean;
  is_featured?: number;
  is_recommended?: number;
  is_trial?: number;
  labelcolor?: string;
  price?: number;
  status?: number;
  title?: string;
  trial_days?: number;
  updated_at?: string;
}
