/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Product {
  id?: number;
  long_description?: string | null;
  name?: string;
  product_category_id?: number;
  short_description?: string | null;
}
