/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductCategory {
  description?: string | null;
  idProductCategory?: number;
  label?: string;
}
