/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface User {
  Enterprise_idEnterprise?: number | null;
  avatar?: string;
  createdAt?: string;
  default_language?: string | null;
  email?: string;
  email_signature?: string | null;
  first_name?: string;
  google_auth_secret?: string | null;
  id?: number;
  is_activated?: boolean;
  is_verified?: boolean;
  last_activity?: string | null;
  last_ip?: string | null;
  last_login?: string | null;
  last_name?: string;
  linkedIn?: string | null;
  plan_id?: number;
  role?: string;
  telephone?: string | null;
  updatedAt?: string;
  will_expire?: string;
}
