/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface BusinessesUpdateIdPut$Params {
  id: number;
      body: {
'need'?: string;
'approach'?: string;
'stage'?: string;
'client_constraints'?: string | null;
'business_type'?: string;
'case_level'?: string;
'total_turnover'?: string | null;
'potential_time_for_delivery'?: string | null;
'case_started_date'?: string;
'current_supplier'?: string | null;
'previous_vc'?: string | null;
'turnover_signable'?: string | null;
'notes'?: string | null;
'closed_date'?: string | null;
'_idLead'?: number;
}
}

export function businessesUpdateIdPut(http: HttpClient, rootUrl: string, params: BusinessesUpdateIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, businessesUpdateIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

businessesUpdateIdPut.PATH = '/businesses/update/{id}';
