/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface BusinessesNextActionBusinessIdGet$Params {

/**
 * Business ID
 */
  businessId: number;
}

export function businessesNextActionBusinessIdGet(http: HttpClient, rootUrl: string, params: BusinessesNextActionBusinessIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, businessesNextActionBusinessIdGet.PATH, 'get');
  if (params) {
    rb.path('businessId', params.businessId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

businessesNextActionBusinessIdGet.PATH = '/businesses/next-action/{businessId}';
