/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { User } from '../../models/user';

export interface UserGetSoloBizdevsPost$Params {
  offset?: number;
  limit?: number;
}

export function userGetSoloBizdevsPost(http: HttpClient, rootUrl: string, params?: UserGetSoloBizdevsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'count'?: number;
'rows'?: Array<User>;
}>> {
  const rb = new RequestBuilder(rootUrl, userGetSoloBizdevsPost.PATH, 'post');
  if (params) {
    rb.query('offset', params.offset, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'count'?: number;
      'rows'?: Array<User>;
      }>;
    })
  );
}

userGetSoloBizdevsPost.PATH = '/user/get-solo-bizdevs';
