/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ContactsGetContactsByLeadLeadIdGet$Params {

/**
 * ID of the Lead
 */
  leadId: number;

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;
}

export function contactsGetContactsByLeadLeadIdGet(http: HttpClient, rootUrl: string, params: ContactsGetContactsByLeadLeadIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'count'?: number;
'rows'?: Array<{
}>;
}>> {
  const rb = new RequestBuilder(rootUrl, contactsGetContactsByLeadLeadIdGet.PATH, 'get');
  if (params) {
    rb.path('leadId', params.leadId, {});
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'count'?: number;
      'rows'?: Array<{
      }>;
      }>;
    })
  );
}

contactsGetContactsByLeadLeadIdGet.PATH = '/contacts/get-contacts-by-lead/{leadId}';
