import { Injectable } from "@angular/core";


@Injectable({
  providedIn: 'root'
})
export class CountryAndRegionService {
 COUNTRIES= [
    {"country": "Afghanistan", "code": "AFG", "region": "South Asia"},
    {"country": "Albania", "code": "ALB", "region": "Southeast Europe"},
    {"country": "Algeria", "code": "DZA", "region": "North Africa"},
    {"country": "Andorra", "code": "AND", "region": "Southern Europe"},
    {"country": "Angola", "code": "AGO", "region": "Southern Africa"},
    {"country": "Antigua and Barbuda", "code": "ATG", "region": "Caribbean"},
    {"country": "Argentina", "code": "ARG", "region": "South America"},
    {"country": "Armenia", "code": "ARM", "region": "Caucasus"},
    {"country": "Australia", "code": "AUS", "region": "Oceania"},
    {"country": "Austria", "code": "AUT", "region": "Central Europe"},
    {"country": "Azerbaijan", "code": "AZE", "region": "Caucasus"},
    {"country": "Bahamas", "code": "BHS", "region": "Caribbean"},
    {"country": "Bahrain", "code": "BHR", "region": "Middle East"},
    {"country": "Bangladesh", "code": "BGD", "region": "South Asia"},
    {"country": "Barbados", "code": "BRB", "region": "Caribbean"},
    {"country": "Belarus", "code": "BLR", "region": "Eastern Europe"},
    {"country": "Belgium", "code": "BEL", "region": "Western Europe"},
    {"country": "Belize", "code": "BLZ", "region": "Central America"},
    {"country": "Benin", "code": "BEN", "region": "West Africa"},
    {"country": "Bhutan", "code": "BTN", "region": "South Asia"},
    {"country": "Bolivia", "code": "BOL", "region": "South America"},
    {"country": "Bosnia and Herzegovina", "code": "BIH", "region": "Southeast Europe"},
    {"country": "Botswana", "code": "BWA", "region": "Southern Africa"},
    {"country": "Brazil", "code": "BRA", "region": "South America"},
    {"country": "Brunei", "code": "BRN", "region": "Southeast Asia"},
    {"country": "Bulgaria", "code": "BGR", "region": "Southeast Europe"},
    {"country": "Burkina Faso", "code": "BFA", "region": "West Africa"},
    {"country": "Burundi", "code": "BDI", "region": "East Africa"},
    {"country": "Cabo Verde", "code": "CPV", "region": "West Africa"},
    {"country": "Cambodia", "code": "KHM", "region": "Southeast Asia"},
    {"country": "Cameroon", "code": "CMR", "region": "Central Africa"},
    {"country": "Canada", "code": "CAN", "region": "North America"},
    {"country": "Central African Republic", "code": "CAF", "region": "Central Africa"},
    {"country": "Chad", "code": "TCD", "region": "Central Africa"},
    {"country": "Chile", "code": "CHL", "region": "South America"},
    {"country": "China", "code": "CHN", "region": "East Asia"},
    {"country": "Colombia", "code": "COL", "region": "South America"},
    {"country": "Comoros", "code": "COM", "region": "East Africa"},
    {"country": "Congo", "code": "COG", "region": "Central Africa"},
    {"country": "Costa Rica", "code": "CRI", "region": "Central America"},
    {"country": "Croatia", "code": "HRV", "region": "Southeast Europe"},
    {"country": "Cuba", "code": "CUB", "region": "Caribbean"},
    {"country": "Cyprus", "code": "CYP", "region": "Mediterranean"},
    {"country": "Czech Republic", "code": "CZE", "region": "Central Europe"},
    {"country": "Denmark", "code": "DNK", "region": "Northern Europe"},
    {"country": "Djibouti", "code": "DJI", "region": "East Africa"},
    {"country": "Dominica", "code": "DMA", "region": "Caribbean"},
    {"country": "Dominican Republic", "code": "DOM", "region": "Caribbean"},
    {"country": "Ecuador", "code": "ECU", "region": "South America"},
    {"country": "Egypt", "code": "EGY", "region": "North Africa"},
    {"country": "El Salvador", "code": "SLV", "region": "Central America"},
    {"country": "Equatorial Guinea", "code": "GNQ", "region": "Central Africa"},
    {"country": "Eritrea", "code": "ERI", "region": "East Africa"},
    {"country": "Estonia", "code": "EST", "region": "Northern Europe"},
    {"country": "Eswatini", "code": "SWZ", "region": "Southern Africa"},
    {"country": "Ethiopia", "code": "ETH", "region": "East Africa"},
    {"country": "Fiji", "code": "FJI", "region": "Oceania"},
    {"country": "Finland", "code": "FIN", "region": "Northern Europe"},
    {"country": "France", "code": "FRA", "region": "Western Europe"},
    {"country": "Gabon", "code": "GAB", "region": "Central Africa"},
    {"country": "Gambia", "code": "GMB", "region": "West Africa"},
    {"country": "Georgia", "code": "GEO", "region": "Caucasus"},
    {"country": "Germany", "code": "DEU", "region": "Central Europe"},
    {"country": "Ghana", "code": "GHA", "region": "West Africa"},
    {"country": "Greece", "code": "GRC", "region": "Southern Europe"},
    {"country": "Grenada", "code": "GRD", "region": "Caribbean"},
    {"country": "Guatemala", "code": "GTM", "region": "Central America"},
    {"country": "Guinea", "code": "GIN", "region": "West Africa"},
    {"country": "Guinea-Bissau", "code": "GNB", "region": "West Africa"},
    {"country": "Guyana", "code": "GUY", "region": "South America"},
    {"country": "Haiti", "code": "HTI", "region": "Caribbean"},
    {"country": "Honduras", "code": "HND", "region": "Central America"},
    {"country": "Hungary", "code": "HUN", "region": "Central Europe"},
    {"country": "Iceland", "code": "ISL", "region": "Northern Europe"},
    {"country": "India", "code": "IND", "region": "South Asia"},
    {"country": "Indonesia", "code": "IDN", "region": "Southeast Asia"},
    {"country": "Iran", "code": "IRN", "region": "Middle East"},
    {"country": "Iraq", "code": "IRQ", "region": "Middle East"},
    {"country": "Ireland", "code": "IRL", "region": "Northern Europe"},
    {"country": "Israel", "code": "ISR", "region": "Middle East"},
    {"country": "Italy", "code": "ITA", "region": "Southern Europe"},
    {"country": "Jamaica", "code": "JAM", "region": "Caribbean"},
    {"country": "Japan", "code": "JPN", "region": "East Asia"},
    {"country": "Jordan", "code": "JOR", "region": "Middle East"},
    {"country": "Kazakhstan", "code": "KAZ", "region": "Central Asia"},
    {"country": "Kenya", "code": "KEN", "region": "East Africa"},
    {"country": "Kiribati", "code": "KIR", "region": "Oceania"},
    {"country": "Korea, North", "code": "PRK", "region": "East Asia"},
    {"country": "Korea, South", "code": "KOR", "region": "East Asia"},
    {"country": "Kosovo", "code": "XKX", "region": "Southeast Europe"},
    {"country": "Kuwait", "code": "KWT", "region": "Middle East"},
    {"country": "Kyrgyzstan", "code": "KGZ", "region": "Central Asia"},
    {"country": "Laos", "code": "LAO", "region": "Southeast Asia"},
    {"country": "Latvia", "code": "LVA", "region": "Northern Europe"},
    {"country": "Lebanon", "code": "LBN", "region": "Middle East"},
    {"country": "Lesotho", "code": "LSO", "region": "Southern Africa"},
    {"country": "Liberia", "code": "LBR", "region": "West Africa"},
    {"country": "Libya", "code": "LBY", "region": "North Africa"},
    {"country": "Liechtenstein", "code": "LIE", "region": "Central Europe"},
    {"country": "Lithuania", "code": "LTU", "region": "Northern Europe"},
    {"country": "Luxembourg", "code": "LUX", "region": "Western Europe"},
    {"country": "Madagascar", "code": "MDG", "region": "East Africa"},
    {"country": "Malawi", "code": "MWI", "region": "East Africa"},
    {"country": "Malaysia", "code": "MYS", "region": "Southeast Asia"},
    {"country": "Maldives", "code": "MDV", "region": "South Asia"},
    {"country": "Mali", "code": "MLI", "region": "West Africa"},
    {"country": "Malta", "code": "MLT", "region": "Southern Europe"},
    {"country": "Marshall Islands", "code": "MHL", "region": "Oceania"},
    {"country": "Mauritania", "code": "MRT", "region": "West Africa"},
    {"country": "Mauritius", "code": "MUS", "region": "East Africa"},
    {"country": "Mexico", "code": "MEX", "region": "North America"},
    {"country": "Micronesia", "code": "FSM", "region": "Oceania"},
    {"country": "Moldova", "code": "MDA", "region": "Eastern Europe"},
    {"country": "Monaco", "code": "MCO", "region": "Western Europe"},
    {"country": "Mongolia", "code": "MNG", "region": "East Asia"},
    {"country": "Montenegro", "code": "MNE", "region": "Southeast Europe"},
    {"country": "Morocco", "code": "MAR", "region": "North Africa"},
    {"country": "Mozambique", "code": "MOZ", "region": "East Africa"},
    {"country": "Myanmar", "code": "MMR", "region": "Southeast Asia"},
    {"country": "Namibia", "code": "NAM", "region": "Southern Africa"},
    {"country": "Nauru", "code": "NRU", "region": "Oceania"},
    {"country": "Nepal", "code": "NPL", "region": "South Asia"},
    {"country": "Netherlands", "code": "NLD", "region": "Western Europe"},
    {"country": "New Zealand", "code": "NZL", "region": "Oceania"},
    {"country": "Nicaragua", "code": "NIC", "region": "Central America"},
    {"country": "Niger", "code": "NER", "region": "West Africa"},
    {"country": "Nigeria", "code": "NGA", "region": "West Africa"},
    {"country": "North Macedonia", "code": "MKD", "region": "Southeast Europe"},
    {"country": "Norway", "code": "NOR", "region": "Northern Europe"},
    {"country": "Oman", "code": "OMN", "region": "Middle East"},
    {"country": "Pakistan", "code": "PAK", "region": "South Asia"},
    {"country": "Palau", "code": "PLW", "region": "Oceania"},
    {"country": "Panama", "code": "PAN", "region": "Central America"},
    {"country": "Papua New Guinea", "code": "PNG", "region": "Oceania"},
    {"country": "Paraguay", "code": "PRY", "region": "South America"},
    {"country": "Peru", "code": "PER", "region": "South America"},
    {"country": "Philippines", "code": "PHL", "region": "Southeast Asia"},
    {"country": "Poland", "code": "POL", "region": "Central Europe"},
    {"country": "Portugal", "code": "PRT", "region": "Southern Europe"},
    {"country": "Qatar", "code": "QAT", "region": "Middle East"},
    {"country": "Romania", "code": "ROU", "region": "Southeast Europe"},
    {"country": "Russia", "code": "RUS", "region": "Eastern Europe/North Asia"},
    {"country": "Rwanda", "code": "RWA", "region": "East Africa"},
    {"country": "Saint Kitts and Nevis", "code": "KNA", "region": "Caribbean"},
    {"country": "Saint Lucia", "code": "LCA", "region": "Caribbean"},
    {"country": "Saint Vincent and the Grenadines", "code": "VCT", "region": "Caribbean"},
    {"country": "Samoa", "code": "WSM", "region": "Oceania"},
    {"country": "San Marino", "code": "SMR", "region": "Southern Europe"},
    {"country": "Sao Tome and Principe", "code": "STP", "region": "Central Africa"},
    {"country": "Saudi Arabia", "code": "SAU", "region": "Middle East"},
    {"country": "Senegal", "code": "SEN", "region": "West Africa"},
    {"country": "Serbia", "code": "SRB", "region": "Southeast Europe"},
    {"country": "Seychelles", "code": "SYC", "region": "East Africa"},
    {"country": "Sierra Leone", "code": "SLE", "region": "West Africa"},
    {"country": "Singapore", "code": "SGP", "region": "Southeast Asia"},
    {"country": "Slovakia", "code": "SVK", "region": "Central Europe"},
    {"country": "Slovenia", "code": "SVN", "region": "Southeast Europe"},
    {"country": "Solomon Islands", "code": "SLB", "region": "Oceania"},
    {"country": "Somalia", "code": "SOM", "region": "East Africa"},
    {"country": "South Africa", "code": "ZAF", "region": "Southern Africa"},
    {"country": "South Sudan", "code": "SSD", "region": "East Africa"},
    {"country": "Spain", "code": "ESP", "region": "Southern Europe"},
    {"country": "Sri Lanka", "code": "LKA", "region": "South Asia"},
    {"country": "Sudan", "code": "SDN", "region": "North Africa"},
    {"country": "Suriname", "code": "SUR", "region": "South America"},
    {"country": "Sweden", "code": "SWE", "region": "Northern Europe"},
    {"country": "Switzerland", "code": "CHE", "region": "Central Europe"},
    {"country": "Syria", "code": "SYR", "region": "Middle East"},
    {"country": "Taiwan", "code": "TWN", "region": "East Asia"},
    {"country": "Tajikistan", "code": "TJK", "region": "Central Asia"},
    {"country": "Tanzania", "code": "TZA", "region": "East Africa"},
    {"country": "Thailand", "code": "THA", "region": "Southeast Asia"},
    {"country": "Togo", "code": "TGO", "region": "West Africa"},
    {"country": "Tonga", "code": "TON", "region": "Oceania"},
    {"country": "Trinidad and Tobago", "code": "TTO", "region": "Caribbean"},
    {"country": "Tunisia", "code": "TUN", "region": "North Africa"},
    {"country": "Turkey", "code": "TUR", "region": "Middle East/Southeast Europe"},
    {"country": "Turkmenistan", "code": "TKM", "region": "Central Asia"},
    {"country": "Tuvalu", "code": "TUV", "region": "Oceania"},
    {"country": "Uganda", "code": "UGA", "region": "East Africa"},
    {"country": "Ukraine", "code": "UKR", "region": "Eastern Europe"},
    {"country": "United Arab Emirates", "code": "ARE", "region": "Middle East"},
    {"country": "United Kingdom", "code": "GBR", "region": "Northern Europe"},
    {"country": "United States", "code": "USA", "region": "North America"},
    {"country": "Uruguay", "code": "URY", "region": "South America"},
    {"country": "Uzbekistan", "code": "UZB", "region": "Central Asia"},
    {"country": "Vanuatu", "code": "VUT", "region": "Oceania"},
    {"country": "Vatican City", "code": "VAT", "region": "Southern Europe"},
    {"country": "Venezuela", "code": "VEN", "region": "South America"},
    {"country": "Vietnam", "code": "VNM", "region": "Southeast Asia"},
    {"country": "Yemen", "code": "YEM", "region": "Middle East"},
    {"country": "Zambia", "code": "ZMB", "region": "Southern Africa"},
    {"country": "Zimbabwe", "code": "ZWE", "region": "Southern Africa"}
  ]

  getCountriesByRegion(region: string) {
    if (!region) return this.COUNTRIES;
    return this.COUNTRIES.filter(country => 
      country.region.toLowerCase().includes(region.toLowerCase())
    );
  }


// In your CountryService (country.service.ts)
  getRegionByCountry(countryName: string): string | undefined {
    if (!countryName) return undefined;
    const foundCountry = this.COUNTRIES.find(country => 
      country.country.toLowerCase() === countryName.toLowerCase()
    );
    
    return foundCountry ? foundCountry.region : undefined;
  }


  
  getAllRegions(): string[] {
    const regions = new Set(this.COUNTRIES.map(country => country.region));
    return Array.from(regions).sort();
  }

  getAllCountries(): string[] {
    const countries = new Set(this.COUNTRIES.map(country => country.country));
    return Array.from(countries).sort();
  }
    
}