/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Contact } from '../../models/contact';

export interface ContactsGetByMeetingMeetingIdGet$Params {
  meetingId: number;
  page?: number;
  limit?: number;
}

export function contactsGetByMeetingMeetingIdGet(http: HttpClient, rootUrl: string, params: ContactsGetByMeetingMeetingIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'count'?: number;
'rows'?: Array<Contact>;
}>> {
  const rb = new RequestBuilder(rootUrl, contactsGetByMeetingMeetingIdGet.PATH, 'get');
  if (params) {
    rb.path('meetingId', params.meetingId, {});
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'count'?: number;
      'rows'?: Array<Contact>;
      }>;
    })
  );
}

contactsGetByMeetingMeetingIdGet.PATH = '/contacts/get-by-meeting/{meetingId}';
