/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ContactHasMeetingUnlinkMeetingMeetingIdIdDelete$Params {

/**
 * Contact ID
 */
  id: number;

/**
 * Meeting ID
 */
  meetingId: number;
}

export function contactHasMeetingUnlinkMeetingMeetingIdIdDelete(http: HttpClient, rootUrl: string, params: ContactHasMeetingUnlinkMeetingMeetingIdIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, contactHasMeetingUnlinkMeetingMeetingIdIdDelete.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('meetingId', params.meetingId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

contactHasMeetingUnlinkMeetingMeetingIdIdDelete.PATH = '/contact-has-meeting/unlink-meeting/{meetingId}/{id}';
