/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Gateway } from '../../models/gateway';

export interface GatewayCreatePost$Params {
      body: Array<{
'id'?: number;
'name'?: string;
'currency'?: string;

/**
 * 1 = active, 0 = inactive
 */
'status'?: number;
}>
}

export function gatewayCreatePost(http: HttpClient, rootUrl: string, params: GatewayCreatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<Gateway>> {
  const rb = new RequestBuilder(rootUrl, gatewayCreatePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Gateway>;
    })
  );
}

gatewayCreatePost.PATH = '/gateway/create';
