/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface EnterprisesCreatePost$Params {
      body: {
'name'?: string;
'sector'?: 'Technology' | 'Healthcare' | 'Education' | 'Finance' | 'Retail' | 'Logistics' | 'Manufacturing' | 'Media';
'email_domain'?: string;
'website'?: string;
'contact_email'?: string;
'country'?: number;
'address'?: string;
'logo'?: Blob;
}
}

export function enterprisesCreatePost(http: HttpClient, rootUrl: string, params: EnterprisesCreatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, enterprisesCreatePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

enterprisesCreatePost.PATH = '/enterprises/create';
