/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Enterprise } from '../../models/enterprise';

export interface EnterprisesGetByIdIdGet$Params {
  id: number;
}

export function enterprisesGetByIdIdGet(http: HttpClient, rootUrl: string, params: EnterprisesGetByIdIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'count'?: number;
'rows'?: Array<Enterprise>;
}>> {
  const rb = new RequestBuilder(rootUrl, enterprisesGetByIdIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'count'?: number;
      'rows'?: Array<Enterprise>;
      }>;
    })
  );
}

enterprisesGetByIdIdGet.PATH = '/enterprises/get-by-id/{id}';
