/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface CompetitorsUpdateIdPut$Params {

/**
 * ID of the competitor to update
 */
  id: number;
      body: {
'name'?: string;
'sector'?: string;
'headquater_location'?: string;
'reference_clients'?: string;
'product_line'?: string;
'website'?: string | null;
'notes'?: string | null;
}
}

export function competitorsUpdateIdPut(http: HttpClient, rootUrl: string, params: CompetitorsUpdateIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, competitorsUpdateIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

competitorsUpdateIdPut.PATH = '/competitors/update/{id}';
