/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface PlansIdPut$Params {

/**
 * ID of the plan to update
 */
  id: number;
      body: {
'title'?: string;
'labelcolor'?: string;
'iconname'?: string;
'price'?: number;
'is_featured'?: number;
'is_recommended'?: number;
'is_trial'?: number;
'days'?: number;
'trial_days'?: number;

/**
 * JSON string containing feature limits and flags
 */
'data'?: string;
}
}

export function plansIdPut(http: HttpClient, rootUrl: string, params: PlansIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, plansIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

plansIdPut.PATH = '/plans/{id}';
